#!/bin/sh
# Cloudflare Pages build step (Build command: `sh build.sh`, output directory: `frontend`).
#
# Points the static site at the API. Set AUTORACK_API_BASE in the Pages
# project's environment variables, e.g. https://api.autorack.example
set -eu
cd "$(dirname "$0")"

API="${AUTORACK_API_BASE:-}"
API="${API%/}"
case "$API" in
  ""|https://*) ;;
  *) echo "AUTORACK_API_BASE must be empty or start with https:// (got '$API')" >&2; exit 1 ;;
esac

cat > config.js <<CFG
// Generated by build.sh at deploy time.
window.AUTORACK_CONFIG = { apiBase: "$API" };
CFG

# connect-src needs the API origin (scheme://host[:port]) when it differs from the site.
ORIGIN=$(printf '%s' "$API" | sed -E 's#^(https://[^/]+).*#\1#')
sed -i.bak "s#__API_ORIGIN__#${ORIGIN}#" _headers && rm -f _headers.bak

echo "Autorack frontend configured for API: ${API:-same origin}"
