"""Remote surface for the desktop operator GUI (admin_gui.py).

admin_gui.py talks to a SQLite file directly when it's running on the same
machine as the database. When the app is hosted somewhere the operator
isn't -- e.g. PythonAnywhere, which offers no SSH or filesystem mounting on
the free tier -- the GUI instead points at this module's routes over
HTTPS, in "remote mode".

Bearer-token authenticated, cookieless, fails closed. Three shapes:

  POST /admin-api/rpc     read-only lookups, dispatched by name from RPC_OPS
  POST /admin-api/action  mutating operations, dispatched by name from
                           ACTION_OPS -- each handler performs its own
                           db.record_audit() call before mutating, lifted
                           verbatim from the matching admin_gui.py closure
  POST /admin-api/sql     the SQL console, mirrored from SqlConsoleTab

Nothing here accepts a client-supplied SQL string except /sql itself --
every other operation is a named, parameterized function, closed by
construction. This is deliberate: the SQL console is already an
intentional full-access escape hatch (gated by "unsafe mode" + audit), and
adding a second, accidental one (e.g. a generic "call any db.* function by
name" dispatcher) would undermine that boundary instead of narrowing it.

GET /admin-api/ping is the auth handshake the GUI uses before trusting a
saved base_url + token.

RPC_OPS/ACTION_OPS are plain module-level functions, not Flask view code,
specifically so admin_gui.py can import and call them directly in "local
mode" (same machine as the DB, no HTTP round trip) -- one implementation
of each operation, shared by both transports, rather than a second copy
of the same logic living in the GUI. See AdminApp.call() in admin_gui.py.
"""

from __future__ import annotations

import base64
import contextlib
import hmac
import os
import secrets
import sqlite3
import tempfile
from datetime import UTC, datetime, timedelta
from pathlib import Path

from flask import Blueprint, jsonify, request

import auth
import backup
import barcode
import billing
import db
import maintenance
import manifest_ingest
import reports
from sqlstore import SQL

# A filename, not a credential. The token itself is the file's
# contents, generated by admin_api_token.py.
TOKEN_FILENAME = "admin_api_token"  # noqa: S105
MAX_TABLE_PAGE_LIMIT = 500

# Upper bound on accounts.loose_suffix_len. barcode.MIN_SUFFIX_LEN is the
# lower one and lives in the engine because both languages clamp to it;
# the upper bound has no engine meaning, it just stops an operator typing a
# value long enough that tier 6 can never produce a key. Enforced in the
# database too -- see migrations/0009.
MAX_SUFFIX_LEN = 20


def _load_or_create_token(path: Path) -> str:
    """Mirrors app.py's _load_or_create_secret_key -- same reasoning:
    minting a fresh token per process would silently break any GUI that
    saved the previous one, including across the very restart the operator
    triggers when deploying this feature.

    Created with O_CREAT|O_EXCL, not a plain write. Two workers starting
    together (gunicorn --workers N on a first deploy) both find the file
    absent, both mint a value, and both write -- so half the processes end
    up with a different secret than the other half, and sessions/CSRF
    tokens issued by one are rejected by the next. O_EXCL makes exactly one
    writer win; the losers re-read what the winner wrote.
    """
    try:
        existing = path.read_text().strip()
        if existing:
            return existing
    except FileNotFoundError:
        pass
    token = secrets.token_hex(32)
    path.parent.mkdir(parents=True, exist_ok=True)
    try:
        fd = os.open(path, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o600)
    except FileExistsError:
        return path.read_text().strip()
    with os.fdopen(fd, "w") as fh:
        fh.write(token)
    with contextlib.suppress(OSError):  # best effort, as in app.py
        path.chmod(0o600)
    return token


def _linked(row: sqlite3.Row | None, what: str) -> sqlite3.Row:
    """Assert a foreign-key-guaranteed row is present. See app.py's twin.

    `manifests.account_id` is NOT NULL with a foreign key and foreign keys
    are enforced, so the account always exists. db.get_account is still
    honestly typed `Row | None` because it is also called with ids from
    request parameters.
    """
    if row is None:
        raise ApiError(f"{what} referenced by a foreign key is missing", 500)
    return row


def _row(row):
    return dict(row) if row is not None else None


def _rows(rows):
    return [dict(r) for r in rows]


class ApiError(Exception):
    def __init__(self, message: str, status: int = 400):
        super().__init__(message)
        self.status = status


def _require(params: dict, *keys):
    missing = [k for k in keys if params.get(k) in (None, "")]
    if missing:
        raise ApiError(f"missing required field(s): {', '.join(missing)}")


# ---------------------------------------------------------------------------
# Read-only lookups: (conn, params) -> JSON-safe data.
#
# "db_path" is a caller-injected params key (set by admin_gui.py's local
# dispatch from self.db_path, or by the /rpc route below from
# app.config["DB_PATH"]) -- never something a remote client supplies
# itself. Only overview_stats uses it.
# ---------------------------------------------------------------------------


def op_list_accounts(conn, params):
    return _rows(db.list_accounts(conn))


def op_account_detail(conn, params):
    _require(params, "account_id")
    account_id = int(params["account_id"])
    return {
        "account": _row(db.get_account(conn, account_id)),
        "users": _rows(db.list_users_for_account(conn, account_id)),
    }


def op_overview_stats(conn, params):
    db_path = Path(params["db_path"])
    size = db_path.stat().st_size if db_path.exists() else 0
    wal_path = Path(str(db_path) + "-wal")
    wal_size = wal_path.stat().st_size if wal_path.exists() else 0
    accounts = db.query_one_required(conn, SQL["operator.count_accounts"])["n"]
    active_shifts = db.query_one_required(
        conn,
        SQL["operator.count_active_shifts"],
    )["n"]
    scans_today = db.query_one_required(conn, SQL["operator.count_scans_today_utc"])["n"]
    open_exceptions = db.query_one_required(conn, SQL["operator.count_open_exceptions"])["n"]
    hourly_rows = db.query(
        conn,
        SQL["operator.scans_per_hour_last_24h"],
    )
    counts = [0] * 24
    for row in hourly_rows:
        counts[int(row["hr"])] = row["n"]
    return {
        "db_path": str(db_path),
        "size": size,
        "wal_size": wal_size,
        "accounts": accounts,
        "active_shifts": active_shifts,
        "scans_today": scans_today,
        "open_exceptions": open_exceptions,
        "hourly": counts,
    }


def op_table_columns(conn, params):
    _require(params, "table")
    return db.table_columns(conn, params["table"])


def op_table_page(conn, params):
    _require(params, "table")
    limit = min(int(params.get("limit", 100)), MAX_TABLE_PAGE_LIMIT)
    offset = max(int(params.get("offset", 0)), 0)
    rows, total = db.table_page(
        conn,
        params["table"],
        limit=limit,
        offset=offset,
        order_by=params.get("order_by"),
        order_dir=params.get("order_dir", "DESC"),
        filters=params.get("filters") or {},
    )
    return {"rows": _rows(rows), "total": total}


def op_live_feed(conn, params):
    rows = db.query(
        conn,
        SQL["operator.live_feed"],
    )
    return _rows(rows)


def op_scan_forensics(conn, params):
    _require(params, "scan_uuid")
    scan_uuid = params["scan_uuid"]
    scan = db.get_scan(conn, scan_uuid)
    if not scan:
        raise ApiError("scan not found", 404)
    session = db.get_session(conn, scan["session_id"])
    shift = db.get_shift(conn, session["shift_id"]) if session else None
    worker = (
        db.query_one(conn, SQL["workers.get_worker"], (session["worker_id"],)) if session else None
    )
    account = db.get_account(conn, shift["account_id"]) if shift else None
    manifest_ids = db.get_shift_manifest_ids(conn, shift["id"]) if shift else []

    norm = barcode.normalize(
        scan["raw_payload"], suffix_len=account["loose_suffix_len"] if account else 8
    )
    raw_bytes = scan["raw_payload"].encode("utf-8", errors="replace")

    idx = manifest_ingest.build_match_index(conn, account, manifest_ids) if account else None
    candidates = {}
    winning_tier = None
    if idx is not None:
        match_result = idx.match(scan["raw_payload"])
        candidates = {int(t): ids for t, ids in match_result.candidates_by_tier.items()}
        winning_tier = int(match_result.tier) if match_result.tier is not None else None

    return {
        "scan": _row(scan),
        "worker": _row(worker),
        "account": _row(account),
        "shift": _row(shift),
        "norm_keys": {int(t): k for t, k in norm.keys.items()},
        "gs1": norm.gs1.__dict__ if norm.gs1 else None,
        "raw_hex": raw_bytes.hex(" "),
        "raw_ascii": scan["raw_payload"],
        "candidates": candidates,
        "winning_tier": winning_tier,
    }


def op_normalizer_match(conn, params):
    _require(params, "raw")
    raw = params["raw"]
    account_id = params.get("account_id")
    account = db.get_account(conn, int(account_id)) if account_id else None
    norm = barcode.normalize(raw, suffix_len=account["loose_suffix_len"] if account else 8)
    match = None
    if account:
        manifest_ids = [m["id"] for m in db.list_committed_manifests(conn, account["id"])]
        idx = manifest_ingest.build_match_index(conn, account, manifest_ids)
        match_result = idx.match(raw)
        match = {
            "tier": int(match_result.tier) if match_result.tier is not None else None,
            "is_resolved": match_result.is_resolved,
            "manifest_line_id": match_result.manifest_line_id,
            "needs_confirmation": match_result.needs_confirmation,
            "candidates_by_tier": {
                int(t): ids for t, ids in match_result.candidates_by_tier.items()
            },
        }
    return {
        "normalized": norm.normalized,
        "gs1": norm.gs1.__dict__ if norm.gs1 else None,
        "gtin_info": norm.gtin_info.__dict__ if norm.gtin_info else None,
        "keys": {int(t): k for t, k in norm.keys.items()},
        "match": match,
    }


def op_manifests_and_shifts(conn, params):
    manifests = db.query(conn, SQL["operator.list_all_manifests"])
    shifts = db.query(conn, SQL["operator.list_all_shifts"])
    return {"manifests": _rows(manifests), "shifts": _rows(shifts)}


def op_manifest_collisions(conn, params):
    _require(params, "manifest_id")
    manifest_id = int(params["manifest_id"])
    manifest = db.get_manifest(conn, manifest_id)
    if not manifest:
        raise ApiError("manifest not found", 404)
    account = _linked(db.get_account(conn, manifest["account_id"]), "account")
    lines = [(r["id"], r["raw_barcode"]) for r in db.get_manifest_lines(conn, manifest_id)]
    report = barcode.analyze_collisions(lines, suffix_len=account["loose_suffix_len"])
    return {"warnings": report.warnings()}


def op_shift_join_token(conn, params):
    _require(params, "shift_id")
    shift = db.get_shift(conn, int(params["shift_id"]))
    if not shift:
        raise ApiError("shift not found", 404)
    return {"token": shift["token"]}


def op_billing_summary(conn, params):
    _require(params, "account_id")
    account_id = int(params["account_id"])
    events = db.billing_events_for_account(conn, account_id)
    return {
        "events": _rows(events),
        "net_owed_cents": billing.net_amount_owed_cents(conn, account_id),
        "savings_cents": billing.savings_to_date_cents(conn, account_id),
    }


def op_savings_report_html(conn, params):
    # Returns rendered HTML rather than writing to disk (unlike
    # reports.write_savings_report) -- the destination path the operator
    # picks is on their own machine, not this server's, so the content has
    # to cross the wire and be written client side. See admin_gui.py's
    # BillingTab._generate_report.
    _require(params, "account_id")
    account_id = int(params["account_id"])
    account = db.get_account(conn, account_id)
    if not account:
        raise ApiError("account not found", 404)
    return {
        "filename": reports.default_report_filename(account),
        "html": reports.generate_savings_report_html(conn, account_id),
    }


def op_savings_reports_all_html(conn, params):
    return {
        "reports": [
            {
                "filename": reports.default_report_filename(a),
                "html": reports.generate_savings_report_html(conn, a["id"]),
            }
            for a in db.list_accounts(conn)
        ]
    }


RPC_OPS = {
    "list_accounts": op_list_accounts,
    "account_detail": op_account_detail,
    "overview_stats": op_overview_stats,
    "table_columns": op_table_columns,
    "table_page": op_table_page,
    "live_feed": op_live_feed,
    "scan_forensics": op_scan_forensics,
    "normalizer_match": op_normalizer_match,
    "manifests_and_shifts": op_manifests_and_shifts,
    "manifest_collisions": op_manifest_collisions,
    "shift_join_token": op_shift_join_token,
    "billing_summary": op_billing_summary,
    "savings_report_html": op_savings_report_html,
    "savings_reports_all_html": op_savings_reports_all_html,
}


# ---------------------------------------------------------------------------
# Mutating actions: (conn, actor, params) -> JSON-safe data. Each performs
# its own db.record_audit() call before mutating, lifted verbatim from the
# matching admin_gui.py tab closure -- see that module's AccountsTab /
# ManifestsShiftsTab / BillingTab for the local-mode originals this
# mirrors. `actor` is "operator-gui" in local mode, or
# "operator-api:<remote addr>" when dispatched over HTTP -- see the /action
# route and AdminApp.call() in admin_gui.py.
# ---------------------------------------------------------------------------


def act_account_create(conn, actor, params):
    _require(params, "name", "email")
    name = params["name"].strip()
    email = params["email"].strip().lower()
    price_cents = int(params.get("price_per_catch_cents", 0))
    free_allowance = int(params.get("free_allowance", 0))
    account_timezone = params.get("timezone") or "UTC"
    if db.get_user_by_email(conn, email):
        raise ApiError(f"a user with email {email} already exists.")
    new_password = auth.generate_relay_password()
    with db.transaction(conn):
        account_id = db.create_account(
            conn, name, price_cents, free_allowance, timezone=account_timezone
        )
        db.create_user(conn, account_id, email, auth.hash_password(new_password), role="owner")
        db.record_audit(
            conn,
            actor=actor,
            action="account.create",
            target_table="accounts",
            target_id=str(account_id),
            after={"name": name, "email": email},
        )
    return {"account_id": account_id, "email": email, "password": new_password}


def act_account_update(conn, actor, params):
    _require(params, "account_id")
    account_id = int(params["account_id"])
    fields = {
        k: params[k]
        for k in (
            "name",
            "plan",
            "price_per_catch_cents",
            "free_allowance",
            "loose_suffix_len",
            "loose_match_enabled",
            "worker_self_resolve",
            "timezone",
        )
        if k in params
    }
    before = _row(db.get_account(conn, account_id))
    if before is None:
        raise ApiError("account not found", 404)
    # Validate before auditing, so a rejected update leaves no audit row
    # claiming a change that never happened. The database enforces this too
    # (migrations/0009), but a 400 here is a better answer than a 500 out of
    # a trigger, and the operator gets told what the bound is.
    if "loose_suffix_len" in fields:
        try:
            suffix_len = int(fields["loose_suffix_len"])
        except (TypeError, ValueError) as exc:
            raise ApiError("loose_suffix_len must be an integer", 400) from exc
        if not barcode.MIN_SUFFIX_LEN <= suffix_len <= MAX_SUFFIX_LEN:
            raise ApiError(
                f"loose_suffix_len must be between {barcode.MIN_SUFFIX_LEN} and {MAX_SUFFIX_LEN}",
                400,
            )
        fields["loose_suffix_len"] = suffix_len
    db.record_audit(
        conn,
        actor=actor,
        action="account.update",
        target_table="accounts",
        target_id=str(account_id),
        before=before,
        after=fields,
    )
    db.update_account_fields(conn, account_id, **fields)
    return {"ok": True}


def act_account_status(conn, actor, params):
    _require(params, "account_id")
    account_id = int(params["account_id"])
    before = _row(db.get_account(conn, account_id))
    if before is None:
        raise ApiError("account not found", 404)
    new_status = "active" if before["status"] == "suspended" else "suspended"
    db.record_audit(
        conn,
        actor=actor,
        action="account.status",
        target_table="accounts",
        target_id=str(account_id),
        before=before,
        after={"status": new_status},
    )
    db.set_account_status(conn, account_id, new_status)
    return {"status": new_status}


def act_account_grant_credit(conn, actor, params):
    _require(params, "account_id", "cents", "reason")
    account_id = int(params["account_id"])
    cents = int(params["cents"])
    reason = params["reason"].strip()
    if not reason:
        raise ApiError("a reason is required.")
    db.record_audit(
        conn,
        actor=actor,
        action="account.grant_credit",
        target_table="accounts",
        target_id=str(account_id),
        after={"cents": cents, "reason": reason},
    )
    credit_id = db.grant_credit(conn, account_id, cents, reason, actor)
    return {"credit_id": credit_id}


def act_account_impersonate_link(conn, actor, params):
    _require(params, "account_id")
    account_id = int(params["account_id"])
    # Milliseconds -- see auth._expiry for why the precision matters.
    expires = (datetime.now(UTC) + timedelta(minutes=5)).strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"
    token = db.create_impersonation_token(conn, account_id, None, expires)
    db.record_audit(
        conn,
        actor=actor,
        action="account.impersonate_link",
        target_table="accounts",
        target_id=str(account_id),
        after={"expires_at": expires},
    )
    return {"token": token, "expires_at": expires}


def act_user_create(conn, actor, params):
    _require(params, "account_id", "email")
    account_id = int(params["account_id"])
    email = params["email"].strip().lower()
    role = params.get("role", "manager")
    if db.get_user_by_email(conn, email):
        raise ApiError(f"a user with email {email} already exists.")
    new_password = auth.generate_relay_password()
    with db.transaction(conn):
        user_id = db.create_user(
            conn, account_id, email, auth.hash_password(new_password), role=role
        )
        db.record_audit(
            conn,
            actor=actor,
            action="user.create",
            target_table="users",
            target_id=str(user_id),
            after={"email": email, "role": role, "account_id": account_id},
        )
    return {"user_id": user_id, "email": email, "password": new_password}


def act_user_update(conn, actor, params):
    _require(params, "user_id")
    user_id = int(params["user_id"])
    before_row = db.get_user(conn, user_id)
    if before_row is None:
        raise ApiError("user not found", 404)
    before = dict(before_row)
    new_email = (params.get("email") or before["email"]).strip().lower()
    new_role = params.get("role") or before["role"]
    email_changed = new_email != before["email"]
    role_changed = new_role != before["role"]
    if email_changed:
        existing = db.get_user_by_email(conn, new_email)
        if existing and existing["id"] != user_id:
            raise ApiError(f"a user with email {new_email} already exists.")
    if (
        role_changed
        and before["role"] == "owner"
        and new_role != "owner"
        and db.count_owners_for_account(conn, before["account_id"]) <= 1
    ):
        raise ApiError("cannot demote the last owner of an account.")
    if email_changed:
        db.record_audit(
            conn,
            actor=actor,
            action="user.update_email",
            target_table="users",
            target_id=str(user_id),
            before={"email": before["email"]},
            after={"email": new_email},
        )
        db.update_user_email(conn, user_id, new_email)
    if role_changed:
        db.record_audit(
            conn,
            actor=actor,
            action="user.update_role",
            target_table="users",
            target_id=str(user_id),
            before={"role": before["role"]},
            after={"role": new_role},
        )
        db.update_user_role(conn, user_id, new_role)
    return {"ok": True}


def act_user_delete(conn, actor, params):
    _require(params, "user_id")
    user_id = int(params["user_id"])
    before = db.get_user(conn, user_id)
    if before is None:
        return {"ok": True}
    db.record_audit(
        conn,
        actor=actor,
        action="user.delete",
        target_table="users",
        target_id=str(user_id),
        before={"email": before["email"], "role": before["role"]},
    )
    db.delete_user(conn, user_id)
    return {"ok": True}


def act_user_password_reset(conn, actor, params):
    _require(params, "user_id")
    user_id = int(params["user_id"])
    user = db.get_user(conn, user_id)
    if user is None:
        raise ApiError("user not found", 404)
    new_password = auth.generate_relay_password()
    db.record_audit(
        conn,
        actor=actor,
        action="user.password_reset",
        target_table="users",
        target_id=str(user_id),
        after={"email": user["email"]},
    )
    db.update_user_password(conn, user_id, auth.hash_password(new_password))
    return {"email": user["email"], "password": new_password}


def act_manifest_regenerate_keys(conn, actor, params):
    _require(params, "manifest_id")
    manifest_id = int(params["manifest_id"])
    manifest = db.get_manifest(conn, manifest_id)
    if not manifest:
        raise ApiError("manifest not found", 404)
    account = _linked(db.get_account(conn, manifest["account_id"]), "account")
    db.record_audit(
        conn,
        actor=actor,
        action="manifest.regenerate_keys",
        target_table="manifests",
        target_id=str(manifest_id),
    )
    report = manifest_ingest.regenerate_keys(
        conn, manifest_id, bool(account["loose_match_enabled"]), account["loose_suffix_len"]
    )
    return {"warnings": report.warnings()}


def act_shift_revoke(conn, actor, params):
    _require(params, "shift_id")
    shift_id = int(params["shift_id"])
    before = db.get_shift(conn, shift_id)
    if before is None:
        raise ApiError("shift not found", 404)
    db.record_audit(
        conn,
        actor=actor,
        action="shift.revoke",
        target_table="shifts",
        target_id=str(shift_id),
        before=dict(before),
    )
    db.revoke_shift(conn, shift_id)
    return {"ok": True}


def act_billing_reverse_event(conn, actor, params):
    _require(params, "event_id", "reason")
    event_id = int(params["event_id"])
    reason = params["reason"].strip()
    if not reason:
        raise ApiError("a reason is required.")
    reversal_id = billing.reverse_billing_event(conn, event_id, reason, actor)
    return {"reversal_id": reversal_id}


ACTION_OPS = {
    "account.create": act_account_create,
    "account.update": act_account_update,
    "account.status": act_account_status,
    "account.grant_credit": act_account_grant_credit,
    "account.impersonate_link": act_account_impersonate_link,
    "user.create": act_user_create,
    "user.update": act_user_update,
    "user.delete": act_user_delete,
    "user.password_reset": act_user_password_reset,
    "manifest.regenerate_keys": act_manifest_regenerate_keys,
    "shift.revoke": act_shift_revoke,
    "billing.reverse_event": act_billing_reverse_event,
}


def run_backup(db_path: Path, photos_dir: Path) -> dict:
    """Shared by the /backup route (remote) and admin_gui.py's local mode
    -- runs backup.backup_everything and returns file content inline
    (base64) rather than just a path, since in remote mode the caller is
    on a different machine than backup_data/. Not audited: matches the
    pre-existing local behavior, which never called db.record_audit for
    backups either (see AdminApp.run_backup_now)."""
    result = backup.backup_everything(db_path, photos_dir)
    payload = {
        "db": {
            "filename": result["db"].name,
            "content_b64": base64.b64encode(result["db"].read_bytes()).decode("ascii"),
        }
    }
    payload["photos"] = None  # type: ignore[assignment]  # widened below
    if result["photos"]:
        payload["photos"] = {
            "filename": result["photos"].name,
            "content_b64": base64.b64encode(result["photos"].read_bytes()).decode("ascii"),
        }
    return payload


def run_restore(kind: str, content: bytes, db_path: Path, photos_dir: Path) -> None:
    """Shared by the /restore route (remote) and admin_gui.py's local
    mode. `content` is the uploaded backup file's raw bytes -- written to
    a temp file here so backup.restore_backup/restore_appeal_photos (which
    both take a path) can operate on it unchanged.

    A database restore replaces the live file underneath a running process.
    backup.restore_backup's precondition ("no other process holds the
    database open") was documented and then not met: this ran inside the
    Flask app with per-request connections open and match-index caches
    populated, so requests in flight could read a half-restored file and
    the caches would keep serving pre-restore data afterwards.

    The maintenance gate closes the in-process half of that -- new requests
    get 503, and every derived cache is dropped once the file has been
    swapped. The cross-process half (gunicorn siblings, an operator's
    script) is still an operational requirement, not something this can
    enforce; see maintenance.py.
    """
    if kind not in ("db", "photos"):
        raise ApiError("kind must be 'db' or 'photos'")
    suffix = ".zip" if kind == "photos" else ".db"
    with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as tmp:
        tmp.write(content)
        tmp_path = Path(tmp.name)
    try:
        if kind == "photos":
            # Photo files are write-once after upload and are addressed by
            # path, so extracting over them needs no gate.
            backup.restore_appeal_photos(tmp_path, photos_dir)
        else:
            with maintenance.restoring():
                backup.backup_database(db_path)  # safety snapshot of current state first
                backup.restore_backup(tmp_path, db_path)
                # Keyed on (database identity, shift id, bundle_version) --
                # a restored file can reuse all three while holding
                # different manifest lines.
                manifest_ingest.clear_match_index_cache()
    finally:
        tmp_path.unlink(missing_ok=True)


def run_sql(conn, sql_text: str, unsafe: bool, actor: str) -> dict:
    """Shared by the /sql route (remote) and admin_gui.py's local mode.

    Server-enforced read-only unless unsafe=True -- a caller's claim that a
    statement is read-only is never trusted (see db.set_read_only's
    docstring: a CTE can prefix a write and still look like a SELECT).
    Every unsafe execution is audited.
    """
    sql_text = sql_text.strip()
    if not sql_text:
        raise ApiError("sql is required")
    try:
        if unsafe:
            db.record_audit(conn, actor=actor, action="sql.unsafe_execute", after={"sql": sql_text})
            try:
                cur = conn.execute(sql_text)
            except sqlite3.ProgrammingError:
                conn.executescript(sql_text)
                return {"multi_statement": True}
        else:
            db.set_read_only(conn)
            cur = conn.execute(sql_text)
        if cur.description:
            columns = [d[0] for d in cur.description]
            rows = [list(r) for r in cur.fetchall()]
            return {"columns": columns, "rows": rows}
        return {"rowcount": cur.rowcount}
    except sqlite3.Error as e:
        raise ApiError(str(e)) from e
    finally:
        if not unsafe:
            db.set_read_only(conn, False)


# ---------------------------------------------------------------------------
# Flask wiring
# ---------------------------------------------------------------------------


def register_admin_api_routes(app, get_db) -> None:
    token_path = app.config["DB_PATH"].parent / TOKEN_FILENAME
    api_token = _load_or_create_token(token_path)

    def _check_auth():
        # A logged-in owner's browser must never be walkable into these
        # routes -- reject session-cookie auth outright, independent of
        # the bearer check below, rather than merely not requiring it.
        if request.cookies.get(auth.SESSION_COOKIE_NAME):
            return False
        header = request.headers.get("Authorization", "")
        if not header.startswith("Bearer "):
            return False
        supplied = header[len("Bearer ") :]
        return hmac.compare_digest(supplied, api_token)

    bp = Blueprint("admin_api", __name__, url_prefix="/admin-api")

    @bp.before_request
    def _auth_gate():
        if not _check_auth():
            return jsonify({"error": "unauthorized"}), 401
        return None

    @bp.route("/ping", methods=["GET"])
    def ping():
        return jsonify({"ok": True})

    @bp.route("/rpc", methods=["POST"])
    def rpc():
        body = request.get_json(silent=True) or {}
        # `fn` is untrusted JSON: it can be absent, or any type at all.
        # str() keeps the dict lookup total instead of raising on, say, a
        # list, and an unknown name already returns 404 below.
        name = str(body.get("fn") or "")
        handler = RPC_OPS.get(name)
        if handler is None:
            return jsonify({"error": f"unknown operation: {name}"}), 404
        conn = get_db()
        params = dict(body.get("params") or {})
        params["db_path"] = str(app.config["DB_PATH"])
        try:
            result = handler(conn, params)
            return jsonify({"result": result})
        except ApiError as e:
            return jsonify({"error": str(e)}), e.status
        except (ValueError, LookupError) as e:
            return jsonify({"error": str(e)}), 400

    @bp.route("/action", methods=["POST"])
    def action():
        body = request.get_json(silent=True) or {}
        name = str(body.get("fn") or "")  # see rpc() above
        handler = ACTION_OPS.get(name)
        if handler is None:
            return jsonify({"error": f"unknown operation: {name}"}), 404
        conn = get_db()
        actor = f"operator-api:{request.remote_addr}"
        try:
            result = handler(conn, actor, body.get("params") or {})
            return jsonify({"result": result})
        except ApiError as e:
            return jsonify({"error": str(e)}), e.status
        except (ValueError, LookupError) as e:
            return jsonify({"error": str(e)}), 400

    @bp.route("/backup", methods=["POST"])
    def backup_route():
        result = run_backup(app.config["DB_PATH"], app.config["APPEAL_PHOTOS_DIR"])
        return jsonify({"result": result})

    @bp.route("/restore", methods=["POST"])
    def restore_route():
        body = request.get_json(silent=True) or {}
        content_b64 = body.get("content_b64")
        if not content_b64:
            return jsonify({"error": "content_b64 is required"}), 400
        try:
            content = base64.b64decode(content_b64)
        except Exception:
            return jsonify({"error": "invalid content_b64"}), 400
        try:
            run_restore(
                str(body.get("kind") or ""),
                content,
                app.config["DB_PATH"],
                app.config["APPEAL_PHOTOS_DIR"],
            )
            return jsonify({"result": {"ok": True}})
        except ApiError as e:
            return jsonify({"error": str(e)}), e.status
        except FileNotFoundError as e:
            return jsonify({"error": str(e)}), 400

    @bp.route("/sql", methods=["POST"])
    def sql_console():
        body = request.get_json(silent=True) or {}
        conn = get_db()
        actor = f"operator-api:{request.remote_addr}"
        try:
            result = run_sql(conn, body.get("sql") or "", bool(body.get("unsafe")), actor)
            return jsonify({"result": result})
        except ApiError as e:
            return jsonify({"error": str(e)}), e.status

    app.register_blueprint(bp)
