"""Initial schema: warehouses, people, orders, scans, billing, audit.

Revision ID: 0001
Revises:
Create Date: 2026-09-24 02:50:12.268270
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rate_limit_hits",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("bucket", sa.String(length=64), nullable=False),
        sa.Column("key", sa.String(length=320), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_rate_limit_lookup", "rate_limit_hits", ["bucket", "key", "created_at"], unique=False)
    op.create_table(
        "warehouses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("owner_email", sa.String(length=320), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column(
            "subscription_status",
            sa.Enum(
                "pilot",
                "trialing",
                "active",
                "past_due",
                "unpaid",
                "canceled",
                "incomplete",
                "incomplete_expired",
                "paused",
                name="subscription_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("trial_ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("past_due_since", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_at_period_end", sa.Boolean(), nullable=False),
        sa.Column("stripe_customer_id", sa.String(length=255), nullable=True),
        sa.Column("stripe_subscription_id", sa.String(length=255), nullable=True),
        sa.Column("join_code", sa.String(length=16), nullable=False),
        sa.Column("loose_match_enabled", sa.Boolean(), nullable=False),
        sa.Column("suffix_len", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("suffix_len BETWEEN 6 AND 14", name="ck_warehouses_suffix_len"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("join_code"),
        sa.UniqueConstraint("stripe_customer_id"),
        sa.UniqueConstraint("stripe_subscription_id"),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=True),
        sa.Column("actor_type", sa.String(length=20), nullable=False),
        sa.Column("actor_id", sa.String(length=64), nullable=True),
        sa.Column("actor_label", sa.String(length=320), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target_type", sa.String(length=32), nullable=True),
        sa.Column("target_id", sa.String(length=64), nullable=True),
        sa.Column(
            "details", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_log_created_at"), "audit_log", ["created_at"], unique=False)
    op.create_index(op.f("ix_audit_log_warehouse_id"), "audit_log", ["warehouse_id"], unique=False)
    op.create_table(
        "devices",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_agent", sa.String(length=300), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(op.f("ix_devices_warehouse_id"), "devices", ["warehouse_id"], unique=False)
    op.create_table(
        "stripe_events",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=100), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column(
            "role",
            sa.Enum("owner", "manager", name="user_role", native_enum=False, create_constraint=True, length=32),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_users_warehouse_id"), "users", ["warehouse_id"], unique=False)
    op.create_table(
        "workers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("pin_hash", sa.String(length=255), nullable=False),
        sa.Column("pin_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_workers_warehouse_id"), "workers", ["warehouse_id"], unique=False)
    op.create_index(
        "uq_workers_active_pin",
        "workers",
        ["warehouse_id", "pin_fingerprint"],
        unique=True,
        postgresql_where=sa.text("active"),
    )
    op.create_table(
        "barcode_aliases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("alias_key", sa.String(length=500), nullable=False),
        sa.Column("target_key", sa.String(length=500), nullable=False),
        sa.Column("note", sa.String(length=300), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("warehouse_id", "alias_key", name="uq_aliases_warehouse_key"),
    )
    op.create_index(op.f("ix_barcode_aliases_warehouse_id"), "barcode_aliases", ["warehouse_id"], unique=False)
    op.create_table(
        "import_batches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=True),
        sa.Column("uploaded_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("orders_created", sa.Integer(), nullable=False),
        sa.Column("lines_created", sa.Integer(), nullable=False),
        sa.Column("orders_skipped", sa.Integer(), nullable=False),
        sa.Column(
            "warnings", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["uploaded_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_import_batches_warehouse_id"), "import_batches", ["warehouse_id"], unique=False)
    op.create_table(
        "magic_link_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("requested_ip", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(op.f("ix_magic_link_tokens_user_id"), "magic_link_tokens", ["user_id"], unique=False)
    op.create_table(
        "owner_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sa.String(length=300), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(op.f("ix_owner_sessions_user_id"), "owner_sessions", ["user_id"], unique=False)
    op.create_table(
        "worker_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("worker_id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["worker_id"],
            ["workers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(op.f("ix_worker_sessions_device_id"), "worker_sessions", ["device_id"], unique=False)
    op.create_index(op.f("ix_worker_sessions_warehouse_id"), "worker_sessions", ["warehouse_id"], unique=False)
    op.create_index(op.f("ix_worker_sessions_worker_id"), "worker_sessions", ["worker_id"], unique=False)
    op.create_table(
        "orders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("external_order_number", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "in_progress",
                "completed",
                "flagged",
                "cancelled",
                name="order_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum("manual", "csv", name="order_source", native_enum=False, create_constraint=True, length=32),
            nullable=False,
        ),
        sa.Column("import_batch_id", sa.Uuid(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("assigned_worker_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_worker_id"],
            ["workers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["import_batch_id"],
            ["import_batches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_orders_created_at"), "orders", ["created_at"], unique=False)
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_index(op.f("ix_orders_warehouse_id"), "orders", ["warehouse_id"], unique=False)
    op.create_index(
        "ix_orders_warehouse_status_created", "orders", ["warehouse_id", "status", "created_at"], unique=False
    )
    op.create_index(
        "uq_orders_external_number",
        "orders",
        ["warehouse_id", "external_order_number"],
        unique=True,
        postgresql_where=sa.text("external_order_number IS NOT NULL AND status <> 'cancelled'"),
    )
    op.create_table(
        "order_line_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("expected_barcode", sa.String(length=200), nullable=False),
        sa.Column("normalized_barcode", sa.String(length=200), nullable=False),
        sa.Column("expected_quantity", sa.Integer(), nullable=False),
        sa.Column("scanned_quantity", sa.Integer(), nullable=False),
        sa.Column("sku", sa.String(length=100), nullable=True),
        sa.Column("sku_description", sa.String(length=500), nullable=True),
        sa.Column("location", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("expected_quantity >= 1", name="ck_line_items_expected_qty"),
        sa.CheckConstraint("scanned_quantity >= 0", name="ck_line_items_scanned_qty"),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_id", "normalized_barcode", name="uq_line_items_order_barcode"),
    )
    op.create_index(op.f("ix_order_line_items_order_id"), "order_line_items", ["order_id"], unique=False)
    op.create_index(op.f("ix_order_line_items_warehouse_id"), "order_line_items", ["warehouse_id"], unique=False)
    op.create_table(
        "scan_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("line_item_id", sa.Uuid(), nullable=True),
        sa.Column("intended_line_item_id", sa.Uuid(), nullable=True),
        sa.Column("worker_id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("worker_session_id", sa.Uuid(), nullable=False),
        sa.Column("scanned_barcode", sa.String(length=500), nullable=False),
        sa.Column("normalized_barcode", sa.String(length=500), nullable=False),
        sa.Column(
            "result",
            sa.Enum(
                "match",
                "over_pick",
                "mismatch",
                "review",
                "void",
                name="scan_result",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("is_match", sa.Boolean(), nullable=False),
        sa.Column("match_tier", sa.Integer(), nullable=True),
        sa.Column("client_result", sa.String(length=32), nullable=True),
        sa.Column("voids_scan_id", sa.Uuid(), nullable=True),
        sa.Column("was_offline", sa.Boolean(), nullable=False),
        sa.Column("client_seq", sa.BigInteger(), nullable=True),
        sa.Column("client_scanned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["intended_line_item_id"],
            ["order_line_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["line_item_id"],
            ["order_line_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["voids_scan_id"],
            ["scan_events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["worker_id"],
            ["workers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["worker_session_id"],
            ["worker_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("voids_scan_id"),
    )
    op.create_index(op.f("ix_scan_events_line_item_id"), "scan_events", ["line_item_id"], unique=False)
    op.create_index(op.f("ix_scan_events_order_id"), "scan_events", ["order_id"], unique=False)
    op.create_index("ix_scan_events_warehouse_received", "scan_events", ["warehouse_id", "received_at"], unique=False)
    op.create_index(
        "ix_scan_events_warehouse_worker", "scan_events", ["warehouse_id", "worker_id", "received_at"], unique=False
    )
    op.create_table(
        "order_flags",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("line_item_id", sa.Uuid(), nullable=True),
        sa.Column("scan_event_id", sa.Uuid(), nullable=True),
        sa.Column("worker_id", sa.Uuid(), nullable=True),
        sa.Column(
            "reason",
            sa.Enum(
                "wrong_item_in_location",
                "out_of_stock",
                "damaged",
                "label_unreadable",
                "other",
                name="flag_reason",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("resolution_note", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["line_item_id"],
            ["order_line_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scan_event_id"],
            ["scan_events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["worker_id"],
            ["workers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_order_flags_order_id"), "order_flags", ["order_id"], unique=False)
    op.create_index(op.f("ix_order_flags_warehouse_id"), "order_flags", ["warehouse_id"], unique=False)
    # ### end Alembic commands ###

    # History is append-only. These triggers make that a property of the
    # database rather than a promise of the application: no endpoint bug and
    # no hand-typed UPDATE can rewrite a scan or an audit entry.
    op.execute("""
        CREATE FUNCTION autorack_append_only() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION '% is append-only', TG_TABLE_NAME USING ERRCODE = 'insufficient_privilege';
        END;
        $$ LANGUAGE plpgsql;
    """)
    for table in ("scan_events", "audit_log"):
        op.execute(
            f"CREATE TRIGGER {table}_append_only BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION autorack_append_only()"
        )


def downgrade() -> None:
    for table in ("scan_events", "audit_log"):
        op.execute(f"DROP TRIGGER IF EXISTS {table}_append_only ON {table}")
    op.execute("DROP FUNCTION IF EXISTS autorack_append_only()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_order_flags_warehouse_id"), table_name="order_flags")
    op.drop_index(op.f("ix_order_flags_order_id"), table_name="order_flags")
    op.drop_table("order_flags")
    op.drop_index("ix_scan_events_warehouse_worker", table_name="scan_events")
    op.drop_index("ix_scan_events_warehouse_received", table_name="scan_events")
    op.drop_index(op.f("ix_scan_events_order_id"), table_name="scan_events")
    op.drop_index(op.f("ix_scan_events_line_item_id"), table_name="scan_events")
    op.drop_table("scan_events")
    op.drop_index(op.f("ix_order_line_items_warehouse_id"), table_name="order_line_items")
    op.drop_index(op.f("ix_order_line_items_order_id"), table_name="order_line_items")
    op.drop_table("order_line_items")
    op.drop_index(
        "uq_orders_external_number",
        table_name="orders",
        postgresql_where=sa.text("external_order_number IS NOT NULL AND status <> 'cancelled'"),
    )
    op.drop_index("ix_orders_warehouse_status_created", table_name="orders")
    op.drop_index(op.f("ix_orders_warehouse_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_index(op.f("ix_orders_created_at"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_worker_sessions_worker_id"), table_name="worker_sessions")
    op.drop_index(op.f("ix_worker_sessions_warehouse_id"), table_name="worker_sessions")
    op.drop_index(op.f("ix_worker_sessions_device_id"), table_name="worker_sessions")
    op.drop_table("worker_sessions")
    op.drop_index(op.f("ix_owner_sessions_user_id"), table_name="owner_sessions")
    op.drop_table("owner_sessions")
    op.drop_index(op.f("ix_magic_link_tokens_user_id"), table_name="magic_link_tokens")
    op.drop_table("magic_link_tokens")
    op.drop_index(op.f("ix_import_batches_warehouse_id"), table_name="import_batches")
    op.drop_table("import_batches")
    op.drop_index(op.f("ix_barcode_aliases_warehouse_id"), table_name="barcode_aliases")
    op.drop_table("barcode_aliases")
    op.drop_index("uq_workers_active_pin", table_name="workers", postgresql_where=sa.text("active"))
    op.drop_index(op.f("ix_workers_warehouse_id"), table_name="workers")
    op.drop_table("workers")
    op.drop_index(op.f("ix_users_warehouse_id"), table_name="users")
    op.drop_table("users")
    op.drop_table("stripe_events")
    op.drop_index(op.f("ix_devices_warehouse_id"), table_name="devices")
    op.drop_table("devices")
    op.drop_index(op.f("ix_audit_log_warehouse_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_created_at"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_table("warehouses")
    op.drop_index("ix_rate_limit_lookup", table_name="rate_limit_hits")
    op.drop_table("rate_limit_hits")
    # ### end Alembic commands ###
